# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "baa4d410077cf680589be39bd745c377"
application_url = "https://colin-fp-advertisement-refresh.trycloudflare.com"
embedded = true
name = "store-hours-manager"
handle = "store-hours-manager-4"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://colin-fp-advertisement-refresh.trycloudflare.com/auth/callback",
  "https://colin-fp-advertisement-refresh.trycloudflare.com/auth/shopify/callback",
  "https://colin-fp-advertisement-refresh.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app]
host = "https://e6e8-2804-14c-138-87fe-21fb-b77c-5a5d-28d4.ngrok-free.app"
